# Generated by Django 5.2.12 on 2026-09-15 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0002_importstage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('source', models.CharField(choices=[('mobile.de', 'mobile.de'), ('autoscout24', 'AutoScout24'), ('manual', 'Entered by hand')], default='mobile.de', max_length=32, verbose_name='Source')),
                ('ad_id', models.CharField(db_index=True, max_length=64, verbose_name='Advert number')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Advert link')),
                ('make', models.CharField(blank=True, max_length=64, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='Model')),
                ('version', models.CharField(blank=True, max_length=190, verbose_name='Version')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model year')),
                ('first_registration', models.CharField(blank=True, max_length=16, verbose_name='First registration')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (km)')),
                ('cc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine (cc)')),
                ('power_kw', models.PositiveIntegerField(blank=True, null=True, verbose_name='Power (kW)')),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Power (hp)')),
                ('fuel', models.CharField(blank=True, max_length=32, verbose_name='Fuel')),
                ('gearbox', models.CharField(blank=True, max_length=32, verbose_name='Gearbox')),
                ('colour_exterior', models.CharField(blank=True, max_length=64, verbose_name='Colour')),
                ('condition_new', models.BooleanField(default=False, verbose_name='Brand new')),
                ('accident_free', models.BooleanField(default=False, verbose_name='Accident-free')),
                ('price_gross_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Listed price (EUR)')),
                ('vatable', models.BooleanField(default=False, help_text='MwSt. ausweisbar — the 19% is reclaimable on export. The price stack is only net when this is true.', verbose_name='VAT deductible')),
                ('vat_rate_pct', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='German VAT %')),
                ('seller_name', models.CharField(blank=True, max_length=190, verbose_name='Seller')),
                ('seller_type', models.CharField(choices=[('dealer', 'Dealer'), ('private', 'Private seller'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='Seller type')),
                ('seller_city', models.CharField(blank=True, max_length=128, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=8, verbose_name='Country')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Photos')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw response')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='First seen')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen')),
                ('still_available', models.BooleanField(default=True, verbose_name='Still listed')),
                ('gone_at', models.DateTimeField(blank=True, null=True, verbose_name='Gone since')),
                ('is_simulated', models.BooleanField(default=False, help_text='Came from the built-in simulator, not from mobile.de. Never quote a simulated car to a customer.', verbose_name='Simulated')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_listings', to='car_import.cardeal', verbose_name='Deal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='car_import.vehicle', verbose_name='Car record')),
            ],
            options={
                'verbose_name': 'Supplier listing',
                'verbose_name_plural': 'Supplier listings',
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['make', 'model', 'model_year'], name='car_import__make_da038c_idx'), models.Index(fields=['still_available', 'vatable'], name='car_import__still_a_1ae9e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'ad_id'), name='uniq_listing_per_source')],
            },
        ),
    ]
