# Generated by Django 5.2.12 on 2026-09-16 11:08

import django.db.models.deletion
import django.utils.timezone
import modules.base.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0004_eur1rule_feeschedule_financingplan_fxreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagechangelog',
            name='notification_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped — the stage does not notify'), ('suppressed', 'Suppressed — held by a switch'), ('opted_out', 'Not sent — the customer opted out'), ('awaiting_approval', 'Waiting for an agent to send')], default='pending', max_length=24, verbose_name='Message'),
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='In force from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='In force until')),
                ('source_note', models.CharField(blank=True, help_text="e.g. owner's answers 2026-09-14, the values workbook", max_length=190, verbose_name='Where this came from')),
                ('code', models.CharField(max_length=64, verbose_name='Code')),
                ('name', models.CharField(max_length=190, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=190, verbose_name='Name (English)')),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='Sequence')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('expires', models.BooleanField(default=False, verbose_name='Has an expiry date')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Confidential')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ask_at_stage', models.ForeignKey(blank=True, help_text='Empty means: as soon as the deal exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requirements', to='car_import.importstage', verbose_name='Ask for it at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('program', models.ForeignKey(blank=True, help_text='Leave empty to ask for it on every route', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='car_import.importprogram', verbose_name='Programme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Document requirement',
                'verbose_name_plural': 'Document requirements',
                'ordering': ['program', 'sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=190, verbose_name='Document')),
                ('state', models.CharField(choices=[('missing', 'Not received'), ('uploaded', 'Received, not checked'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='missing', max_length=16, verbose_name='State')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Expires on')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='Why it was rejected')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='car_import.cardeal', verbose_name='Deal')),
                ('file', modules.base.fields.AttachmentForeignKeyField(blank=True, help_text='The scan or photo the customer sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment_relations', to='base.attachment', upload_to='car_import/documents', verbose_name='File')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Checked by')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_documents', to='car_import.documentrequirement', verbose_name='Requirement')),
            ],
            options={
                'verbose_name': 'Deal document',
                'verbose_name_plural': 'Deal documents',
                'ordering': ['deal', 'requirement__sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='Country')),
                ('initiative_type', models.CharField(choices=[('gulf', 'Gulf'), ('european', 'European'), ('other', 'Other')], default='gulf', max_length=16, verbose_name='Type')),
                ('approval_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Approval number')),
                ('status', models.CharField(choices=[('none', 'Not applied'), ('applied', 'Applied'), ('issued', 'Issued'), ('modified', 'Modified'), ('used', 'Used'), ('expired', 'Expired'), ('for_sale', 'Offered for sale'), ('sold', 'Sold')], default='none', max_length=16, verbose_name='Status')),
                ('deposit_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deposit (USD)')),
                ('tier', models.CharField(blank=True, choices=[('medium', 'Medium'), ('full', 'Full')], max_length=16, verbose_name='Tier')),
                ('deposit_paid_on', models.DateField(blank=True, null=True, verbose_name='Deposit paid on')),
                ('refund_due_on', models.DateField(blank=True, help_text='Five years after the deposit was paid', null=True, verbose_name='Refund due on')),
                ('refunded_on', models.DateField(blank=True, null=True, verbose_name='Refunded on')),
                ('modifications_used', models.PositiveIntegerField(default=0, help_text='One is the maximum. The second request is refused.', verbose_name='Modifications used')),
                ('transferable', models.BooleanField(default=False, verbose_name='May be transferred')),
                ('asking_price_egp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Asking price (EGP)')),
                ('participation_split', models.CharField(blank=True, max_length=190, verbose_name='Participation split')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_bought_initiatives', to='base.partner', verbose_name='Buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='car_import.cardeal', verbose_name='Used on deal')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_import_initiatives', to='base.partner', verbose_name='Holder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentrequirement',
            constraint=models.UniqueConstraint(fields=('code', 'program'), name='uniq_doc_requirement'),
        ),
        migrations.AddIndex(
            model_name='dealdocument',
            index=models.Index(fields=['deal', 'state'], name='car_import__deal_id_a1fc63_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealdocument',
            constraint=models.UniqueConstraint(fields=('deal', 'requirement'), name='uniq_deal_document'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['status', 'transferable'], name='car_import__status_420f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['refund_due_on'], name='car_import__refund__d12f16_idx'),
        ),
    ]
