# Generated by Django 5.2.12 on 2026-09-16 11:25

import django.db.models.deletion
import django.utils.timezone
import modules.base.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0005_alter_stagechangelog_notification_state_and_more'),
        ('crm', '0016_lead_lead_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('dropbox_file_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Dropbox file id')),
                ('dropbox_path', models.CharField(blank=True, max_length=500, verbose_name='Path')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File name')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Size')),
                ('is_simulated', models.BooleanField(default=False, help_text='Came from the built-in simulator, not Dropbox', verbose_name='Simulated')),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='Recorded at')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Length (s)')),
                ('direction', models.CharField(choices=[('inbound', 'Incoming'), ('outbound', 'Outgoing'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='Direction')),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Customer number')),
                ('agent_folder', models.CharField(blank=True, max_length=190, verbose_name='Agent folder')),
                ('match_state', models.CharField(choices=[('unmatched', 'No customer found'), ('ambiguous', 'Several customers match'), ('matched', 'Matched'), ('manual', 'Matched by hand')], default='unmatched', max_length=16, verbose_name='Match')),
                ('match_note', models.CharField(blank=True, max_length=255, verbose_name='Match note')),
                ('candidates', models.JSONField(blank=True, default=list, help_text='When several numbers matched, rather than guessing', verbose_name='Possible customers')),
                ('process_state', models.CharField(choices=[('new', 'Downloaded'), ('transcribing', 'Being transcribed'), ('transcribed', 'Transcribed'), ('summarised', 'Summarised'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='new', max_length=16, verbose_name='Processing')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('action_items', models.JSONField(blank=True, default=list, verbose_name='Action items')),
                ('language', models.CharField(blank=True, default='ar', max_length=16, verbose_name='Language')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Error')),
                ('consent_recorded', models.BooleanField(default=False, verbose_name='Consent on file')),
                ('sent_to_customer', models.BooleanField(default=False, verbose_name='Sent to the customer')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_calls', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('audio', modules.base.fields.AttachmentForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment_relations', to='base.attachment', upload_to='car_import/calls', verbose_name='Recording')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='car_import.cardeal', verbose_name='Deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_calls', to='crm.lead', verbose_name='Lead')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_calls', to='base.partner', verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Call recording',
                'verbose_name_plural': 'Call recordings',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['match_state', 'process_state'], name='car_import__match_s_e009e5_idx'), models.Index(fields=['recorded_at'], name='car_import__recorde_051b80_idx')],
            },
        ),
    ]
