# Generated by Django 5.2.12 on 2026-09-16 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0006_callrecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('matched', 'Buyer found'), ('completed', 'Transferred'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16, verbose_name='State')),
                ('asking_price_egp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Asking price (EGP)')),
                ('participation_terms', models.CharField(blank=True, max_length=255, verbose_name='Terms')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Matched')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_initiative_purchases', to='base.partner', verbose_name='Buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='car_import.initiative', verbose_name='Initiative')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Initiative for sale',
                'verbose_name_plural': 'Initiatives for sale',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['state'], name='car_import__state_625e57_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShowroomListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=190, verbose_name='Title')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16, verbose_name='State')),
                ('price_egp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Price (EGP)')),
                ('negotiable', models.BooleanField(default=False, verbose_name='Negotiable')),
                ('licensed', models.BooleanField(default=False, verbose_name='Licensed')),
                ('protection_film', models.BooleanField(default=False, verbose_name='Protection film fitted')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (km)')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Where it is')),
                ('published_to_website', models.BooleanField(default=False, verbose_name='On the website')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Photos')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_import_reservations', to='base.partner', verbose_name='Reserved for')),
                ('sold_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_sales', to='car_import.cardeal', verbose_name='Sold on deal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_listings', to='car_import.vehicle', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Showroom car',
                'verbose_name_plural': 'Showroom cars',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['state', 'published_to_website'], name='car_import__state_05e8c6_idx')],
            },
        ),
    ]
