# Generated by Django 5.2.12 on 2026-09-16 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0007_initiativelisting_showroomlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='has_memory_seats',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_other_tier_option',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_electric_seats',
            field=models.BooleanField(default=False, verbose_name='Electric seats (كراسي كهرباء)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_leather_seats',
            field=models.BooleanField(default=False, verbose_name='Leather seats (كراسي جلد)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_digital_cluster',
            field=models.BooleanField(default=False, verbose_name='Digital cluster (عداد ديجيتال)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_electric_trunk',
            field=models.BooleanField(default=False, verbose_name='Electric boot (شنطة كهرباء)'),
        ),
        migrations.CreateModel(
            name='PricingBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='In force from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='In force until')),
                ('source_note', models.CharField(blank=True, help_text="e.g. owner's answers 2026-09-14, the values workbook", max_length=190, verbose_name='Where this came from')),
                ('name', models.CharField(max_length=120, verbose_name='Band')),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='Order')),
                ('gross_from_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='From (gross EUR)')),
                ('gross_to_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for the top band', max_digits=12, null=True, verbose_name='To (gross EUR)')),
                ('admin_fee_type', models.CharField(choices=[('fixed', 'A fixed amount'), ('percent_of_net', 'A percentage of the net price')], default='percent_of_net', max_length=20, verbose_name='Admin fee is')),
                ('admin_fee_value', models.DecimalField(decimal_places=4, default=0, help_text='An amount, or a percentage — a negative amount is a discount, which the cheapest band actually uses', max_digits=12, verbose_name='Admin fee value')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Deposit %')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pricing band',
                'verbose_name_plural': 'Pricing bands',
                'ordering': ['sequence', 'gross_from_eur'],
            },
        ),
    ]
