# Generated by Django 5.2.12 on 2026-09-16 14:57

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import modules.base.models.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0008_remove_vehicle_has_memory_seats_and_more'),
        ('notifications', '0006_notification_category_notificationcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('message_last_post', models.DateTimeField(blank=True, help_text='Timestamp of the last message posted', null=True, verbose_name='Last Message Date')),
                ('message_bounce', models.PositiveIntegerField(blank=True, default=0, help_text='Counter of bounced emails', null=True)),
                ('message_is_follower', models.BooleanField(blank=True, default=False, help_text='Current user is a follower', null=True)),
                ('message_follower_ids', models.TextField(blank=True, help_text='Cached follower IDs as JSON', null=True)),
                ('message_partners', models.TextField(blank=True, help_text='Cached partner IDs as JSON', null=True)),
                ('activity_state', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_date_deadline', models.DateField(blank=True, null=True)),
                ('activity_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_exception_decoration', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_exception_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Reference')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to the customer'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=16, verbose_name='Status')),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('gross_price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='The number on the German advert — everything else follows from it', max_digits=12, null=True, verbose_name='Price with VAT (EUR)')),
                ('with_eur1', models.BooleanField(default=False, verbose_name='EUR 1 certificate')),
                ('shipping_type', models.CharField(blank=True, choices=[('', 'Standard'), ('vip_roro', 'VIP RORO'), ('container', 'Container')], default='', max_length=16, verbose_name='Shipping')),
                ('port', models.CharField(choices=[('alexandria', 'Alexandria'), ('port_said', 'Port Said')], default='alexandria', max_length=16, verbose_name='Port of arrival')),
                ('collect_from_showroom', models.BooleanField(default=False, verbose_name='Collected from the showroom')),
                ('admin_fee_discount_eur', models.DecimalField(decimal_places=2, default=0, help_text='Never more than the fee itself', max_digits=12, verbose_name='Discount on the admin fee (EUR)')),
                ('vat_rate_pct', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='VAT %')),
                ('fx_rate_egp', models.DecimalField(blank=True, decimal_places=4, help_text='Only to show the customer an indicative figure. The company does not promise a rate', max_digits=12, null=True, verbose_name='EGP per EUR')),
                ('band_label', models.CharField(blank=True, max_length=120, verbose_name='Band used')),
                ('net_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net price (EUR)')),
                ('vat_reclaimable_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='VAT reclaimed (EUR)')),
                ('shipping_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping (EUR)')),
                ('admin_fee_before_discount_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Admin fee (EUR)')),
                ('admin_fee_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Admin fee after discount (EUR)')),
                ('eur1_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='EUR 1 (EUR)')),
                ('shipping_extra_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping option (EUR)')),
                ('total_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total selling price (EUR)')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Deposit %')),
                ('deposit_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposit (EUR)')),
                ('balance_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance (EUR)')),
                ('port_fee_egp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Port fees (EGP)')),
                ('showroom_fee_egp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Showroom collection (EGP)')),
                ('egp_due_on_arrival', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Due on arrival (EGP)')),
                ('total_egp_indicative', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Indicative total (EGP)')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Calculated at')),
                ('pricing_error', models.CharField(blank=True, max_length=255, verbose_name='Why there is no price')),
                ('paid_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid so far (EUR)')),
                ('deposit_covered', models.BooleanField(default=False, verbose_name='Deposit covered')),
                ('fully_paid', models.BooleanField(default=False, verbose_name='Paid in full')),
                ('remaining_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Still owed (EUR)')),
                ('overpaid_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Overpaid (EUR)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('activity_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_activities', to='notifications.activitytype')),
                ('activity_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_activities', to=settings.AUTH_USER_MODEL)),
                ('alias_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alias', to='notifications.alias')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Sales agent')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='car_import.pricingband', verbose_name='Band')),
                ('branch', models.ForeignKey(help_text='Branch where this transaction occurred', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch_set', to='base.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='car_import.cardeal', verbose_name='Deal')),
                ('message_main_attachment_id', models.ForeignKey(blank=True, help_text='Main attachment for this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_main_attachment', to='base.attachment')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_quotes', to='base.partner', verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='car_import.vehicle', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-id'],
            },
            bases=(modules.base.models.mixins.SequenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='#')),
                ('code', models.CharField(max_length=32, verbose_name='Code')),
                ('label', models.CharField(max_length=190, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount')),
                ('currency', models.CharField(default='EUR', max_length=8, verbose_name='Currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='car_import.quote', verbose_name='Quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Quotation line',
                'verbose_name_plural': 'Quotation lines',
                'ordering': ['sequence', 'id'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['state', 'quote_date'], name='car_import__state_26f503_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['partner'], name='car_import__partner_97787a_idx'),
        ),
    ]
