# Generated by Django 5.2.12 on 2026-09-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0009_quote_quoteline_quote_car_import__state_26f503_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='admin_fee_before_discount_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Admin fee (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='admin_fee_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Admin fee after discount (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='balance_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Balance (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='band',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='car_import.pricingband', verbose_name='Band'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='band_label',
            field=models.CharField(blank=True, editable=False, max_length=120, verbose_name='Band used'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='calculated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Calculated at'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deposit_covered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Deposit covered'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deposit_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Deposit (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deposit_pct',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Deposit %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='egp_due_on_arrival',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Due on arrival (EGP)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='eur1_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='EUR 1 (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='fully_paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Paid in full'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='net_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Net price (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overpaid_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Overpaid (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='port_fee_egp',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Port fees (EGP)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pricing_error',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Why there is no price'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='remaining_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Still owed (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Shipping (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_extra_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Shipping option (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='showroom_fee_egp',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Showroom collection (EGP)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_egp_indicative',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Indicative total (EGP)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total selling price (EUR)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='vat_reclaimable_eur',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='VAT reclaimed (EUR)'),
        ),
    ]
