# Generated by Django 5.2.12 on 2026-09-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0010_alter_quote_admin_fee_before_discount_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsvaluation',
            name='basis',
            field=models.CharField(choices=[('payable', 'The amount payable'), ('valuation', 'The value the rate applies to'), ('unknown', 'Not yet confirmed')], default='payable', help_text='Confirmed by the client on 16 September 2026: the figures in the initiative workbook are the amount actually paid', max_length=16, verbose_name='This number is'),
        ),
    ]
