# Generated by Django 5.2.12 on 2026-09-16 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0011_alter_customsvaluation_basis'),
        ('notifications', '0006_notification_category_notificationcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstage',
            name='fallback_text_ar',
            field=models.TextField(blank=True, help_text='Used inside the WhatsApp window and on every other channel. Placeholders: {customer_name} {car_full} {model} {model_year} {vin} {stage_name} {port} {vessel} {eta} {bl_number} {tracking_url} {deal_ref}. Prefer {car_full} over {model} {model_year}: a WhatsApp template may not put two placeholders next to each other, even with a space', verbose_name='Message text (Arabic)'),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=190, verbose_name='Name')),
                ('program', models.CharField(choices=[('personal', 'Personal import'), ('initiative', 'Initiative'), ('commercial', 'Commercial import'), ('any', 'Any programme')], default='any', max_length=24, verbose_name='Programme')),
                ('docx', models.FileField(upload_to='car_import/contract_templates/', verbose_name='Template file')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('is_fillable', models.BooleanField(default=True, verbose_name='Can be filled')),
                ('tokens', models.JSONField(blank=True, default=list, verbose_name='Fields in this template')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Contract template',
                'verbose_name_plural': 'Contract templates',
                'ordering': ['program', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('message_last_post', models.DateTimeField(blank=True, help_text='Timestamp of the last message posted', null=True, verbose_name='Last Message Date')),
                ('message_bounce', models.PositiveIntegerField(blank=True, default=0, help_text='Counter of bounced emails', null=True)),
                ('message_is_follower', models.BooleanField(blank=True, default=False, help_text='Current user is a follower', null=True)),
                ('message_follower_ids', models.TextField(blank=True, help_text='Cached follower IDs as JSON', null=True)),
                ('message_partners', models.TextField(blank=True, help_text='Cached partner IDs as JSON', null=True)),
                ('activity_state', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_date_deadline', models.DateField(blank=True, null=True)),
                ('activity_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_exception_decoration', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_exception_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=16, verbose_name='Status')),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Contract date')),
                ('customer_name', models.CharField(blank=True, max_length=190, verbose_name='Name as on the ID')),
                ('customer_national_id', models.CharField(blank=True, max_length=32, verbose_name='National ID number')),
                ('customer_address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shipping_name', models.CharField(blank=True, help_text='Usually the customer. On the initiative route it may be the initiative holder instead', max_length=190, verbose_name='Ships in the name of')),
                ('car_model', models.CharField(blank=True, max_length=128, verbose_name='Model')),
                ('car_trim', models.CharField(blank=True, max_length=128, verbose_name='Trim')),
                ('car_model_year', models.CharField(blank=True, max_length=8, verbose_name='Model year')),
                ('car_configuration', models.CharField(blank=True, max_length=128, verbose_name='Configuration number')),
                ('total_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total contract value (EUR)')),
                ('down_payment_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Received at signing (EUR)')),
                ('bank_transfer_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bank transfer (EUR)')),
                ('cash_on_bl_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cash on bill of lading (EUR)')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Deposit %')),
                ('instalment_1_date', models.DateField(blank=True, null=True, verbose_name='Payment 1 — date')),
                ('instalment_1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment 1 — amount')),
                ('instalment_2_date', models.DateField(blank=True, null=True, verbose_name='Payment 2 — date')),
                ('instalment_2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment 2 — amount')),
                ('instalment_3_date', models.DateField(blank=True, null=True, verbose_name='Payment 3 — date')),
                ('instalment_3_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment 3 — amount')),
                ('document', models.FileField(blank=True, editable=False, upload_to='car_import/contracts/', verbose_name='Generated contract')),
                ('generated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Generated at')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='Signed on')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('activity_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_activities', to='notifications.activitytype')),
                ('activity_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_next_activities', to=settings.AUTH_USER_MODEL)),
                ('alias_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alias', to='notifications.alias')),
                ('branch', models.ForeignKey(help_text='Branch where this transaction occurred', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch_set', to='base.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='car_import.cardeal', verbose_name='Deal')),
                ('generated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Generated by')),
                ('message_main_attachment_id', models.ForeignKey(blank=True, help_text='Main attachment for this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_main_attachment', to='base.attachment')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='car_import.quote', verbose_name='Quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='car_import.contracttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-id'],
            },
        ),
    ]
