# Generated by Django 5.2.12 on 2026-09-16 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0013_cardeal_accepted_quote_cardeal_initiative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10, verbose_name='#')),
                ('label', models.CharField(blank=True, max_length=190, verbose_name='Label')),
                ('listing_url', models.URLField(blank=True, max_length=500, verbose_name='Advert link')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='The customer chose this one')),
                ('gross_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price with VAT (EUR)')),
                ('with_eur1', models.BooleanField(default=False, verbose_name='EUR 1 certificate')),
                ('shipping_type', models.CharField(blank=True, choices=[('', 'Standard'), ('vip_roro', 'VIP RORO'), ('container', 'Container')], default='', max_length=16, verbose_name='Shipping')),
                ('port', models.CharField(choices=[('alexandria', 'Alexandria'), ('port_said', 'Port Said')], default='alexandria', max_length=16, verbose_name='Port of arrival')),
                ('collect_from_showroom', models.BooleanField(default=False, verbose_name='Collected from the showroom')),
                ('admin_fee_discount_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount on the admin fee (EUR)')),
                ('vat_rate_pct', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='VAT %')),
                ('band_label', models.CharField(blank=True, editable=False, max_length=120, verbose_name='Band used')),
                ('net_eur', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Net (EUR)')),
                ('total_eur', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total (EUR)')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Deposit %')),
                ('deposit_eur', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Deposit (EUR)')),
                ('balance_eur', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Balance (EUR)')),
                ('egp_due_on_arrival', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Due on arrival (EGP)')),
                ('pricing_error', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Why there is no price')),
                ('calculated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Calculated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='car_import.quote', verbose_name='Quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_options', to='car_import.vehicle', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Candidate car',
                'verbose_name_plural': 'Candidate cars',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quoteline',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='car_import.quoteoption', verbose_name='Candidate car'),
        ),
    ]
