# Generated by Django 5.2.12 on 2026-09-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('car_import', '0015_alter_approvalpolicy_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.CharField(blank=True, choices=[('initiative', 'Initiative'), ('personal', 'Personal import'), ('commercial', 'Commercial import'), ('showroom', 'Showroom car'), ('consignment', 'Consignment')], max_length=32, null=True, verbose_name='Programme')),
                ('initiative_type', models.CharField(blank=True, choices=[('gulf', 'Gulf'), ('european', 'European')], max_length=16, null=True, verbose_name='Initiative type')),
                ('model_wanted', models.CharField(blank=True, max_length=128, null=True, verbose_name='Model wanted')),
                ('model_year_wanted', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model year wanted')),
                ('trim_wanted', models.CharField(blank=True, max_length=128, null=True, verbose_name='Trim wanted')),
                ('colour_wanted', models.CharField(blank=True, max_length=64, null=True, verbose_name='Colour wanted')),
                ('condition_wanted', models.CharField(blank=True, choices=[('new', 'Zero'), ('used', 'Used')], max_length=16, null=True, verbose_name='Zero or used')),
                ('budget_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (€)')),
                ('funds_ready_on', models.DateField(blank=True, null=True, verbose_name='Funds ready on')),
                ('residence_country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country of residence')),
                ('is_expat', models.BooleanField(default=False, verbose_name='Egyptian abroad')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.partner', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Qualify customer',
                'verbose_name_plural': 'Qualify customer',
            },
        ),
    ]
