# Generated by Django 5.2.12 on 2026-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0016_qualifycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalpolicy',
            name='subject',
            field=models.CharField(choices=[('car_discount', "Discount on the car's price"), ('fee_discount', "Discount on the company's fees"), ('payment_schedule', 'A payment schedule other than the standard'), ('cancellation', 'Cancellation, refund or settlement'), ('fx_rate', 'The transfer rate and its commission'), ('bank_details', 'Giving out bank account details'), ('complaint', 'A complaint about condition, a missing option or damage'), ('sourcing_outside_eu', 'Sourcing outside Germany or the EU'), ('contract_signature', 'Signing the contract'), ('program_approval', 'Opening a deal on a programme that needs management'), ('consignment_below_band', 'Selling a consigned car below the agreed price band')], max_length=32, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='subject',
            field=models.CharField(choices=[('car_discount', "Discount on the car's price"), ('fee_discount', "Discount on the company's fees"), ('payment_schedule', 'A payment schedule other than the standard'), ('cancellation', 'Cancellation, refund or settlement'), ('fx_rate', 'The transfer rate and its commission'), ('bank_details', 'Giving out bank account details'), ('complaint', 'A complaint about condition, a missing option or damage'), ('sourcing_outside_eu', 'Sourcing outside Germany or the EU'), ('contract_signature', 'Signing the contract'), ('program_approval', 'Opening a deal on a programme that needs management'), ('consignment_below_band', 'Selling a consigned car below the agreed price band')], max_length=32, verbose_name='Subject'),
        ),
    ]
