# Generated by Django 5.2.12 on 2026-10-08 13:32
"""The client's list of 2026-10-07: memory seats among the six tier options,
the people a stage is kept for (the shipping stage), and the EU-made brands."""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_import', '0030_link_tracker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The client's correction of the six options: memory seats, not
        # electric seats. A different option, so a new column rather than a
        # rename — a car with electric seats does not have memory seats. No car
        # had the old one ticked (khaled_test, 2026-10-08).
        migrations.RemoveField(
            model_name='vehicle',
            name='has_electric_seats',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_memory_seats',
            field=models.BooleanField(default=False, verbose_name='Memory seats (كراسي ميموري)'),
        ),
        migrations.AddField(
            model_name='importstage',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='When set, nobody else can move a deal INTO this stage — the shipping stage, for example. Empty: everyone who can edit deals', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Only these people move a deal here'),
        ),
        migrations.CreateModel(
            name='EuMadeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('note', models.CharField(blank=True, help_text='Optional, e.g. which countries or which models', max_length=190, verbose_name='Note')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eu_made', to='car_import.carbrand', verbose_name='Brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'EU-made brand',
                'verbose_name_plural': 'EU-made brands',
                'ordering': ['brand__name'],
            },
        ),
    ]
