# -*- coding: utf-8 -*-
from django.utils.translation import gettext as _

menu_dict = {
    "car_import_main_menu": {
        "name": _("Car Import"),
        "icon": "Car",
        "module": "car_import",
        "sequence": 15,
        "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                           "car_import.operations", "car_import.germany_team",
                           "car_import.management"],
        "children": {
            "car_import_menu_dashboard": {
                "name": _("Dashboard"),
                "icon": "LayoutDashboard",
                "module": "car_import",
                "model": "car_import.cardeal",
                "view_types": "dashboard",
                # Dashboards render as tabs of /dashboard/, keyed by the view's
                # key. EntryView (/genie/<id>/) has no dashboard strategy and
                # quietly falls back to the LIST — which is what this menu
                # showed until now: a table of deals under a dashboard title.
                "url": "/dashboard/?tab=car_import_dashboard_view",
                "sequence": 5,
                "allowed_groups": ["car_import.sales_manager", "car_import.operations",
                                   "car_import.management"],
            },
            "car_import_menu_deals": {
                "name": _("Deals"),
                "icon": "Handshake",
                "module": "car_import",
                "model": "car_import.cardeal",
                "view_types": "kanban,list,form",
                "sequence": 10,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.operations", "car_import.management"],
            },
            "car_import_menu_quotes": {
                "name": _("Quotations"),
                "icon": "Calculator",
                "module": "car_import",
                "model": "car_import.quote",
                "view_types": "list,form",
                "sequence": 15,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.management"],
            },
            "car_import_menu_vehicles": {
                "name": _("Cars"),
                "icon": "CarFront",
                "module": "car_import",
                "model": "car_import.vehicle",
                "view_types": "list,form",
                "sequence": 20,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.germany_team", "car_import.management"],
            },
            "car_import_menu_listings": {
                "name": _("Supplier listings"),
                "icon": "Search",
                "module": "car_import",
                "model": "car_import.supplierlisting",
                "view_types": "list,form",
                "sequence": 25,
                # Not the sales agents: a listing carries the German purchase
                # price, which is cost data they must not see.
                "allowed_groups": ["car_import.sales_manager", "car_import.germany_team",
                                   "car_import.management"],
            },
            "car_import_menu_contracts": {
                "name": _("Contracts"),
                "icon": "FileText",
                "module": "car_import",
                "model": "car_import.contract",
                "view_types": "list,form",
                "sequence": 26,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.operations", "car_import.management"],
            },
            "car_import_menu_consignment": {
                "name": _("Consignment mandates"),
                "icon": "Handshake",
                "module": "car_import",
                "model": "car_import.consignmentmandate",
                "view_types": "list,form",
                "sequence": 24,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.showroom", "car_import.management"],
            },
            "car_import_menu_approval_requests": {
                "name": _("Approval requests"),
                "icon": "ShieldCheck",
                "module": "car_import",
                "model": "car_import.approvalrequest",
                "view_types": "list,form",
                "sequence": 31,
                # Everyone sees the queue — an agent needs to know their own
                # request is waiting. Only management can decide one, which the
                # model permissions enforce.
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.operations", "car_import.management"],
            },
            "car_import_menu_deal_documents": {
                "name": _("Documents"),
                "icon": "FileCheck",
                "module": "car_import",
                "model": "car_import.dealdocument",
                "view_types": "list,form",
                "sequence": 27,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.operations", "car_import.management"],
            },
            "car_import_menu_initiatives": {
                "name": _("Initiatives"),
                "icon": "BadgeCheck",
                "module": "car_import",
                "model": "car_import.initiative",
                "view_types": "list,form",
                "sequence": 28,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.management"],
            },
            "car_import_menu_showroom": {
                "name": _("Showroom cars"),
                "icon": "Store",
                "module": "car_import",
                "model": "car_import.showroomlisting",
                "view_types": "list,form",
                "sequence": 21,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.showroom", "car_import.management"],
            },
            "car_import_menu_initiative_market": {
                "name": _("Initiatives for sale"),
                "icon": "ArrowLeftRight",
                "module": "car_import",
                "model": "car_import.initiativelisting",
                "view_types": "list,form",
                "sequence": 28,
                "allowed_groups": ["car_import.sales_agent", "car_import.sales_manager",
                                   "car_import.management"],
            },
            "car_import_menu_calls": {
                "name": _("Call recordings"),
                "icon": "PhoneCall",
                "module": "car_import",
                "model": "car_import.callrecording",
                "view_types": "list,form",
                "sequence": 29,
                # Internal only. A recording is personal data, and the summaries
                # are for the company rather than the customer.
                "allowed_groups": ["car_import.sales_manager", "car_import.operations",
                                   "car_import.management"],
            },
            "car_import_menu_stage_log": {
                "name": _("Message log"),
                "icon": "Send",
                "module": "car_import",
                "model": "car_import.stagechangelog",
                "view_types": "list",
                "sequence": 30,
                "allowed_groups": ["car_import.sales_manager", "car_import.operations",
                                   "car_import.management"],
            },
            "car_import_menu_configuration": {
                "name": _("Configuration"),
                "icon": "Settings",
                "module": "car_import",
                "sequence": 90,
                "allowed_groups": ["car_import.management"],
                "children": {
                    "car_import_menu_stages": {
                        "name": _("Stages and messages"),
                        "icon": "ListOrdered",
                        "module": "car_import",
                        "model": "car_import.importstage",
                        "view_types": "list,form",
                        "sequence": 10,
                        "allowed_groups": ["car_import.management", "car_import.operations"],
                    },
                    "car_import_menu_doc_requirements": {
                        "name": _("Document checklists"),
                        "icon": "ClipboardList",
                        "module": "car_import",
                        "model": "car_import.documentrequirement",
                        "view_types": "list,form",
                        "sequence": 15,
                        "allowed_groups": ["car_import.management", "car_import.operations"],
                    },
                    "car_import_menu_programs": {
                        "name": _("Import programmes"),
                        "icon": "Route",
                        "module": "car_import",
                        "model": "car_import.importprogram",
                        "view_types": "list,form",
                        "sequence": 20,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_pricing_bands": {
                        "name": _("Pricing bands"),
                        "icon": "Calculator",
                        "module": "car_import",
                        "model": "car_import.pricingband",
                        "view_types": "list,form",
                        "sequence": 25,
                        "allowed_groups": ["car_import.management", "car_import.sales_manager"],
                    },
                    "car_import_menu_contract_templates": {
                        "name": _("Contract templates"),
                        "icon": "FileStack",
                        "module": "car_import",
                        "model": "car_import.contracttemplate",
                        "view_types": "list,form",
                        "sequence": 26,
                        # The lawyer's wording. Management only.
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_approval_policies": {
                        "name": _("Approval rules"),
                        "icon": "ShieldAlert",
                        "module": "car_import",
                        "model": "car_import.approvalpolicy",
                        "view_types": "list,form",
                        "sequence": 24,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_contract_issuers": {
                        "name": _("Contract issuer and signatories"),
                        "icon": "Stamp",
                        "module": "car_import",
                        "model": "car_import.contractissuer",
                        "view_types": "list,form",
                        "sequence": 27,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_fees": {
                        "name": _("Fee schedule"),
                        "icon": "Receipt",
                        "module": "car_import",
                        "model": "car_import.feeschedule",
                        "view_types": "list,form",
                        "sequence": 30,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_financing": {
                        "name": _("Financing plans"),
                        "icon": "CreditCard",
                        "module": "car_import",
                        "model": "car_import.financingplan",
                        "view_types": "list,form",
                        "sequence": 40,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_tax_rules": {
                        "name": _("Tax rules"),
                        "icon": "Percent",
                        "module": "car_import",
                        "model": "car_import.taxrule",
                        "view_types": "list",
                        "sequence": 50,
                        "allowed_groups": ["car_import.management"],
                    },
                    "car_import_menu_deposits": {
                        "name": _("Deposit values"),
                        "icon": "Landmark",
                        "module": "car_import",
                        "model": "car_import.deposittier",
                        "view_types": "list",
                        "sequence": 60,
                        "allowed_groups": ["car_import.management", "car_import.sales_manager"],
                    },
                    "car_import_menu_customs": {
                        "name": _("Customs values"),
                        "icon": "Scale",
                        "module": "car_import",
                        "model": "car_import.customsvaluation",
                        "view_types": "list",
                        "sequence": 70,
                        "allowed_groups": ["car_import.management", "car_import.sales_manager"],
                    },
                    "car_import_menu_price_ranges": {
                        "name": _("Model price ranges"),
                        "icon": "ChartNoAxesColumn",
                        "module": "car_import",
                        "model": "car_import.modelpricerange",
                        "view_types": "list",
                        "sequence": 80,
                        "allowed_groups": ["car_import.management", "car_import.sales_manager"],
                    },
                    "car_import_menu_fx": {
                        "name": _("Exchange rates"),
                        "icon": "ArrowRightLeft",
                        "module": "car_import",
                        "model": "car_import.fxreference",
                        "view_types": "list,form",
                        "sequence": 90,
                        "allowed_groups": ["car_import.management", "car_import.sales_manager"],
                    },
                },
            },
        },
    },
}
